# Generated by Django 4.2.4 on 2023-11-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_vege_receipe_ing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vege',
            name='receipe_ing',
        ),
    ]
