# Generated by Django 4.2.4 on 2023-11-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_alter_vege_receipe_ingr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vege',
            name='receipe_ingr',
            field=models.CharField(default='timezone.now', max_length=500),
        ),
    ]
